repos:
  # Terraform Hooks
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.85.4  # Check for latest version
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_tfsec

  # Basic Pre-Commit Hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: detect-private-key
