baseHelmChart: &baseHelm
  kind: helmchart
  pattern: "*"
  spec:
    version: latest

scms:
  default:
    kind: github
    spec:
      user: jayantverma11
      owner: jayantverma11
      repository: https://github.com/jayantverma11/test-helmchart.git
      token: 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
      username: jayantverma11
      branch: main

sources:
  chart-cluster-autoscaler:
    <<: *baseHelm
    spec:
      name: cluster-autoscaler
      url: https://kubernetes.github.io/autoscaler

conditions: {}

targets:
  chart-cluster-autoscaler:
    name: Update cluster-autoscaler version in input.tf
    kind: terraform/file
    sourceid: chart-cluster-autoscaler
    spec:
      file: templates/eks/inputs.tf
      path: variable.cluster-autoscaler.default

actions:
  default:
    title: Open a GitHub pull request with new helm chart version
    kind: github/pullrequest
    scmid: default
    target:
      - chart-cluster-autoscaler
    spec:
      automerge: false
      mergemethod: squash
      
