baseHelmChart: &baseHelm
  kind: helmchart
  pattern: "*"
  spec:
    version: latest

scms:
  default:
    kind: "github"
    spec:
      user: "jayantverma11"
      owner: "jayantverma11"
      repository: "test-helmchart"
      token: "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"
      username: "jayantverma11"
      branch: "main"

actions:
  helm-charts:
    kind: "github"
    scmid: "helm_chart"
    target:
      - chart-cluster-autoscaler
    spec:
      automerge: false
      description: "Prepend description"
      draft: true
      labels:
        - "dependencies"
        - "epinio"
      title: "Pull Request Title"

sources:
  chart-cluster-autoscaler:
    <<: *baseHelm
    spec:
      name: cluster-autoscaler
      url: https://kubernetes.github.io/autoscaler

conditions: {}

targets:
  chart-cluster-autoscaler:
    name: Update cluster-autoscaler version in input.tf
    scmid: helm_chart
    kind: terraform/file
    sourceid: chart-cluster-autoscaler
    spec:
      file: templates/eks/inputs.tf
      path: variable.cluster-autoscaler.default

