name: Update Helm Charts

on:
  workflow_dispatch: 
jobs:
  update-helm-charts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install updatecli
        run: |
          curl -LO https://github.com/updatecli/updatecli/releases/download/v0.9.0/updatecli_Linux_x86_64.tar.gz
          tar -zxvf updatecli_Linux_x86_64.tar.gz
          mv updatecli /usr/local/bin
