name: Update Helm Charts

on: 
  push:
    branches:
      - main  # Specify the branches you want this workflow to run on push

jobs:
  update-helm-charts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install updatecli
        run: |
          curl -LO https://github.com/updatecli/updatecli/releases/download/v0.9.0/updatecli_Linux_x86_64.tar.gz
          tar -zxvf updatecli_Linux_x86_64.tar.gz
          mv updatecli /usr/local/bin

      - name: check update cli version
        run: |
          updatecli version
          pwd
          cat templates/eks/inputs.tf

      - name: Run updatecli
        run: updatecli apply --config .github/workflows/updatecli.yml          
          
