# updatecli.yaml
sources:
  helm:
    name: "Get Latest Helm Chart Version"
    kind: "helmChart"
    spec:
      url: https://kubernetes.github.io/ingress-nginx
      name: ingress-nginx
      version: latest

targets:
  updateChartVersion:
    name: "Update Helm Chart Version in Codebase"
    kind: "terraform"
    spec:
      file: templates/eks/inputs.tf
      key: variable.NGINX_CHART_VERSION.default
