name: Update Helm Charts

on: 
  push:
    branches:
      - main  # Specify the branches you want this workflow to run on push

jobs:
  update-helm-charts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Python
        # Ensure Python is installed (if not already available on the runner)
        run: |
          sudo apt-get update
          sudo apt-get install -y python3

      - name: Generate updatecli.yaml
        run: |
          output=$(python3 generate_updatecli_yaml_file.py)
          echo "$output"      

      - name: Install updatecli
        run: |
          curl -LO https://github.com/updatecli/updatecli/releases/download/v0.80.0/updatecli_Linux_x86_64.tar.gz
          tar -zxvf updatecli_Linux_x86_64.tar.gz
          mv updatecli /usr/local/bin

      - name: check update cli version
        run: |
          updatecli version
          pwd
          cat templates/eks/inputs.tf

      - name: Run updatecli
        run: updatecli apply --config .github/workflows/updatecli.yml          

      - name: cat update cli version
        run: |
          cat templates/eks/inputs.tf          
