# updatecli.yaml
sources:
  helm:
    name: "Get Latest Helm Chart Version"
    kind: helmChart
    pattern: "*"
    spec:
      url: https://kubernetes.github.io/ingress-nginx
      name: ingress-nginx

targets:
  updateChartVersion:
    name: "Update Helm Chart Version in Codebase"
    kind: terraform
    spec:
      file: templates/eks/inputs.tf
      key: variable.NGINX_CHART_VERSION.default
      value: "{{ .helm.Version }}"

