name: Update Helm Charts

on: 
  push:
    branches:
      - main  # Run this workflow on push to main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.2  # Use latest stable version

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Fetch changed files
        id: changed-files
        uses: tj-actions/changed-files@v44  # Get list of changed files

      - name: Run pre-commit on changed files
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "${{ steps.changed-files.outputs.all_changed_files }}" | xargs pre-commit run --files
