# updatecli.yaml
sources:
  helm:
    name: "Get Latest Helm Chart Version"
    kind: "helmChart"
    spec:
      url: https://kubernetes.github.io/ingress-nginx
      name: ingress-nginx

targets:
  updateChartVersion:
    name: "Update Helm Chart Version in Codebase"
    kind: file
    spec:
      file: templates/eks/inputs.tf
      matchPattern: "(variable \"NGINX_CHART_VERSION\" {\\s*default = \")([^\"]+)(\")"
      replacePattern: "$1{{ source }}$3"      
